version: '3.8'

services:
  app:
    build: .
    container_name: php-review-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-review-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: reviews
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
